fix indentation

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -26,18 +26,16 @@ jobs:
       id: install
     - run: mkdir ~/.kube && echo ${{ secrets.KUBECONFIG }} > ~/.kube/config
     - run: |
-      MANIFEST=projects/${{ inputs.cncf_project }}/{{ $inputs.cncf_project}}
-      if -n ${{ inputs.cncf_project_sub}}; then
-        MANIFEST=$MANIFEST-${{ inputs.cncf_project_sub }}
-      fi
-      MANIFEST=$MANIFEST.yaml
-      if ! test -f "$MANIFEST"; then
-        echo "The provided inputs are invalid."
-        exit 1
-      fi
+        MANIFEST=projects/${{ inputs.cncf_project }}/{{ $inputs.cncf_project}}
+        if -n ${{ inputs.cncf_project_sub}}; then
+          MANIFEST=$MANIFEST-${{ inputs.cncf_project_sub }}
+        fi
+        MANIFEST=$MANIFEST.yaml
+        if ! test -f "$MANIFEST"; then
+          echo "The provided inputs are invalid."
+          exit 1
+        fi
 
-      export VERSION=${{ inputs.version }}
-      envsubst < $MANIFEST > manifest.yaml
-      cat manifest.yaml
-      
-
+        export VERSION=${{ inputs.version }}
+        envsubst < $MANIFEST > manifest.yaml
+        cat manifest.yaml
