fix workflow

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -17,25 +17,28 @@ concurrency:
 
 jobs:
   deploy:
-  runs-on: ubuntu-22.04
-  steps:
-    - uses: action/checkout@v4
-    - uses: azure/setup-kubectl@v4
-      with:
-        version: v1.30.2
-      id: install
-    - run: mkdir ~/.kube && echo ${{ secrets.KUBECONFIG }} > ~/.kube/config
-    - run: |
-        MANIFEST=projects/${{ inputs.cncf_project }}/{{ $inputs.cncf_project}}
-        if -n ${{ inputs.cncf_project_sub}}; then
-          MANIFEST=$MANIFEST-${{ inputs.cncf_project_sub }}
-        fi
-        MANIFEST=$MANIFEST.yaml
-        if ! test -f "$MANIFEST"; then
-          echo "The provided inputs are invalid."
-          exit 1
-        fi
+    runs-on: ubuntu-22.04
+    steps:
+      - uses: action/checkout@v4
+      - uses: azure/setup-kubectl@v4
+        with:
+          version: v1.30.2
+        id: install
+      - run: mkdir ~/.kube && echo ${{ secrets.KUBECONFIG }} > ~/.kube/config
+      - run: |
+          MANIFEST=projects/${{ inputs.cncf_project }}/{{ $inputs.cncf_project}}
+          if -n ${{ inputs.cncf_project_sub}}; then
+            MANIFEST=$MANIFEST-${{ inputs.cncf_project_sub }}
+          fi
+          MANIFEST=$MANIFEST.yaml
+          if ! test -f "$MANIFEST"; then
+            echo "The provided inputs are invalid."
+            exit 1
+          fi
 
-        export VERSION=${{ inputs.version }}
-        envsubst < $MANIFEST > manifest.yaml
-        cat manifest.yaml
+          export VERSION=${{ inputs.version }}
+          envsubst < $MANIFEST > manifest.yaml
+          cat manifest.yaml
+
+    - run: kubectl delete -f manifest.yaml --wait
+      if: always()
